version: "3.9"

services:
  back_end:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - log_volume:/var/www/html/log/

  database:
    image: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=cora
      - MARIADB_ROOT_PASSWORD=secret
    expose:
      - 40000
    ports:
      - "40000:3306"
    volumes:
      - ./deploy/cora.sql:/docker-entrypoint-initdb.d/cora.sql
      - db_volume:/var/lib/mysql

volumes:
  db_volume:
    driver: local
  log_volume:
    driver: local

